version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    #kakfa<scala version>-<kafka version>
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      #PLAINTEXT - 보안방식
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #로컬의 이름
      KAFKA_ADVERTISED_HOST_NAME: localhost
      #Topic:Number of Partition:Number of replication
      KAFKA_CREATE_TOPICS: "Topic:2:1, Topic2:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
